### ISSUE TITLE
Add support of smartling.client_lib_id directive

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/api-sdk-php#19]
Smartling FAPI v1 was extended, now it accepts a string with additional information about client application.

**DoD**:
* Add the new method `setClientUid(String name, String version)` to SDK
* Call of method above is optional. SDK must send in this case
 * Name of SDK = `smartling-api-sdk-php` plus its version
 * Exact format of strings `{"client":"smartling-api-sdk-php","version":"1.0.0" }`
* SDK must add `smartling.client_lib_id` directive to all Upload request into request **params** (not a file body)
* Unit test is added which verifies that any Upload request contains `smartling.client_lib_id` directive

Example of implementation in [java sdk](https://github.com/Smartling/api-sdk-java/commit/dbd1219f8e09855fdb1d7f49f6528234fa157165)

**Comment by dimitrystd** [comment]
Reopened. Current implementation doesn't cover one of important case
>SDK **must** add `smartling.client_lib_id` directive to **all** Upload request....

Let's see on example
```php
sdk = SmartlingFileApi::create('projectId', 'userIdentifier', 'secretKey', null);
sdk->uploadFile('/tmp/1.xml', '1.xml', 'xml');
```
As result file is uploaded but without `smartling.client_lib_id` directive.
Updated DoD with unit test

**Comment by paveldhq** [comment]
done
