### ISSUE TITLE
Implement Project Details API

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/api-sdk-php#38]
We need a list of configured project locales in some connectors. Smartling provides separate Projects API which contains one of required method:
```
curl -X GET -H "Authorization: Bearer xxxx" 'https://api.smartling.com/projects-api/v2/projects/xxxx'
```
```json
{
  "response": {
    "code": "SUCCESS",
    "data": {
      "projectId": "xxxx",
      "projectName": "DMS test site",
      "accountUid": "yyyy",
      "archived": false,
      "targetLocales": [
        {
          "localeId": "ru-RU",
          "description": "Russian"
        },
        ...
        {
          "localeId": "es",
          "description": "Spanish (International)"
        }
      ],
      "categories": [],
      "sourceLocaleId": "en-US",
      "sourceLocaleDescription": "English (United States)"
    }
  }
}
```
**DoD**: Add a new Project API client with single API call implementation into v2.x. Rest calls will be added on demand

**Comment by paveldhq** [comment]
Tested:

curl -X GET -H "Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiI4MDgxMTAwNS04MTA3LTQzODQtODljMC01NDMwMWQxNTU0ZWYiLCJleHAiOjE0NTA4MDI2MjcsIm5iZiI6MCwiaWF0IjoxNDUwODAyMzI3LCJpc3MiOiJodHRwczovL3Nzby5zbWFydGxpbmcuY29tL2F1dGgvcmVhbG1zL1NtYXJ0bGluZyIsImF1ZCI6ImF1dGhlbnRpY2F0aW9uLXNlcnZpY2UiLCJzdWIiOiIyNzgzMTljZC00YmFmLTRhMzctOTVmOC0yNGZmODVhNmFjMTQiLCJhenAiOiJhdXRoZW50aWNhdGlvbi1zZXJ2aWNlIiwic2Vzc2lvbl9zdGF0ZSI6ImNjMDU3ZjY4LWQ2ZTQtNDE0YS05MGJhLTVlMDYxMDNmNjcxNyIsImNsaWVudF9zZXNzaW9uIjoiZTBkZDcxNjgtNTJmNy00MWFmLTkyNTUtZTIxNTFmZjI1M2MyIiwiYWxsb3dlZC1vcmlnaW5zIjpbXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIlJPTEVfQVBJX1VTRVIiLCJ1c2VyIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJ2aWV3LXByb2ZpbGUiLCJtYW5hZ2UtYWNjb3VudCJdfX0sInVpZCI6IjQ1NTNkZjU5YzY3YiIsImVtYWlsIjoiYXBpVXNlcithY2NvdW50KzJmMjNlYWFlOUBzbWFydGxpbmcuY29tIiwibmFtZSI6IlRlc3QiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhcGk6VFN3SWlVb2pDUWluWm5KZ1dZQmZiWkVLb0tabVFtIn0.FW2_aGi_VfVqmrwuZlFKDTfqwQ1zp3ytS7xvjOEvjUltbP48TVSxd7aTgqj7wvusnwN84ZbxKC4aUSZ19J7FCvu7QQkvtP0Uds3aEW7n5a6GJlQSq0QLOdqHrRhl1x0U3Wyj6lyf2ersmHuyhROxHOAlnxbbJHW5cL8-NL3UgPY" 'https://api.smartling.com/projects-api/v2/projects/13f3a47e0'


Got empty response.

**Comment by dimitrystd** [comment]
Let's keep it open until call will be moved to separate file in the `Project` folder

**Comment by paveldhq** [comment]
moved
