### ISSUE TITLE
Add logging to sdk

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/api-sdk-php#4]
We implemented tiny and good library that makes communication with Smartling transparent. But end-developer doesn't have ability to research issues if communication doesn't work. We should add logging capability to our library.
**DoD**:
- SDK must log at least all operations with Debug level (uploadFile, getStatus, and so on)
- Each log entry should include request parameters (apikey, locale and so on)
 - Would be nice if we can write to log full GET or POST request that we are going to to send (of course we don't need to include content of file)
- Write response to log (pls format json before writing)
- Of course SDK should write exceptions to log and raise them to a host code
- SDK must not use any existing logging libraries (like `monolog` or `log4php`). End developer should provide logger implementation by yourself if he wants.
 - I think logger interface can look like
```php
Logger {
  abstract public function debug($message, $throwable = null);
  abstract public function info($message, $throwable = null);
  abstract public function warn($message, $throwable = null);
  abstract public function error($message, $throwable = null);
  abstract public function fatal($message, $throwable = null);
}
```

**Comment by dimitrystd** [comment]
Look at PSR-3 standard before starting this task

**Comment by paveldhq** [comment]
dependency psr/log master-dev should be added,
LoggerInterface.php should be removed

**Comment by paveldhq** [comment]
added logging on sdk <=> api operations
