### ISSUE TITLE
API clients don't use DevNullLogger as default value

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/api-sdk-php#40]
After refactoring 81de0449d1bbeeff0a3c4331dde6681bd066ee50 we lost some functionality and made more mandatory parameters. Now user must pass instance of logger interface:
```php
public static function create ( $userIdentifier, $secretKey, LoggerInterface $logger );
public static function create ( $projectId, $userIdentifier, $secretKey, LoggerInterface $logger, $serviceUrl = null );
```
But logger must be optional. If user will call something like
```php
sdk = SmartlingFileApi::create('projectId', 'userIdentifier', 'secretKey', null);
```
then we will get nullpointer exception later.

**DoD**:
Logger is optional parameter in all SDKs

**Comment by paveldhq** [comment]
done
