### ISSUE TITLE
Bad Composer versioning : "v1.x-dev" breaks the code

### ISSUE THREAD

**Issue by cedx** [Smartling/api-sdk-php#51]
I'm using this version constraint with your package :

```json
{
  "require": {
    "smartling/api-sdk-php": "^1.9.19"
  }
}
```

When I'm installing the dependencies with `composer install` or `composer update`, the version "1.x-dev" is installed instead of the version "1.9.x".

The problem is that version "1.x-dev" is not compatible at all with version "1.9".

**Comment by paveldhq** [comment]
@cedx , please use `1.9.x` branch.

1. Make sure you have  added the repository, e.g.:
```
...
 "repositories" : [
    {
      "type" : "vcs",
      "url" :  "git@github.com:Smartling/api-sdk-php.git"
    }
  ],
...
```
2. Then add ```"smartling/api-sdk-php" : "~1.9"``` to `require` section.

**Comment by cedx** [comment]
Thanks for your reply... but I don't share your analysis of the issue (I'm already using the right branch).

I should not have to add the Git repository to my `composer.json` : everything worked fine during the last months. See my previous issue about Composer versioning (https://github.com/Smartling/api-sdk-php/issues/30) : since, I use the same `composer.json` file/settings without any problem (almost one year).

After investigating, this is not an issue with your package, but an issue with Composer resolution : one of my dependencies is using Guzzle v6, but your package is using Guzzle v5. In order to resolve the dependency problem, Composer decided to download the version "1.x-dev" as it is the sole release not having any version constraint about Guzzle.
 
I finally fixed this issue by using your next major version (2.x), which is using Guzzle v6 :

```json
{
  "require": {
    "smartling/api-sdk-php": "^2.0.0"
  }
}
```

It downloads the "2.0.0.x-dev" version of the package which works fine  :)

Sorry to bother you, this issue can be closed as it's related to Composer, not this package, and your next release will definitely resolve my problem.
