### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by roippi** [Smartling/api-sdk-php#55]
Your [docs](http://docs.smartling.com/pages/API/v2/SDKs/) say to `git clone` the repo directly, but `composer require smartling/api-sdk-php` [still installs ~1.9](https://packagist.org/packages/smartling/api-sdk-php) because there has been no 2.0 release.  Can you make one please?

**Comment by paveldhq** [comment]
Hello @roippi,
Smartling uses API v2. Current latest versions of php-sdk is ~1.9.

**Comment by roippi** [comment]
Okay.  Can you release `1.9.20` then?  1.9.19 does not include the latest commit from master, which you are recommending people install via `git clone`.

I'm asking because 1.9.19 uses guzzle 5, which is a blocker for our use.  I can use `dev-master` in composer but I would prefer not to.

**Comment by roippi** [comment]
Also the extra commit in master is https://github.com/Smartling/api-sdk-php/commit/aa0f94d2a4b850c6a38a7dc438145d52b28c9a59, so I assumed you meant the next release to be 2.0.
