### ISSUE TITLE
[request] Add Upload Context File API endpoint

### ISSUE THREAD

**Issue by adl1995** [Smartling/api-sdk-php#56]
Currently, there is no support for the [Context File API](http://help.smartling.com/developers/api/v2/context/upload-context/). I will add it once I get the time, or if someone else wants to do it from the community. For now I'm making the call using PHP cURL.

**Comment by PavelLoparev** [comment]
Hi, @adl1995 
We've added Context API class. It's available since `1.9.24` release (`2.0.0-g5` branch which uses `Guzzle5`) and `3.0.5` release (`3.0.0-g6` branch which uses `Guzzle6`) releases.
