### ISSUE TITLE
Add header with client_id for Context API

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/api-sdk-php#71]
Context API may accept an additional http header which describes requestor. Would be nice to set this header explicit since we migrated to the new context API.

**DoD**:
Add following HTTP header to all Context API callls. No need to add it for Auth of File API calls
```
X-SL-Context-Source: group=connectors;name={connectorName};version={connectorVersion}
```
We already have 2 static properties: `CurrentClientId`; `CurrentClientVersion`. So the real header may look as
```
X-SL-Context-Source: group=connectors;name=drupal-classic-connector;version=3.0.0
```

**Comment by PavelLoparev** [comment]
PR to review: https://github.com/Smartling/api-sdk-php/pull/72

**Comment by PavelLoparev** [comment]
@dimitrystd merged

**Comment by PavelLoparev** [comment]
Drupal connectors are updated:
Classic: https://www.drupal.org/node/2907015
TMGMT: https://www.drupal.org/node/2907016
